spring:
  application:
    name: auth-service
  # redis 服务器配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: ""
    timeout: 60000
    database: 0
    # 连接池属性配置
    lettuce:
      pool:
        # 最小空闲连接数
        min-idle: 5
        # 最大空闲连接数
        max-idle: 10
        # 最大活动的连接数
        max-active: 10
        # 连接最大等待数
        max-wait: 3000
server:
  port: 12018
