server:
  port: 12019
spring:
  application:
    name: gateway-service
  cloud:
    # 注册服务【如果不用配置中心的话，不要引入nacos-config依赖包,否则启动报错】
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 配置gateway网关：https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/
    #     1、SpringCloud Gateway的路由转发必须是满足所有的predicates才可以算匹配成功，从而被转发。当然，相同的Predicate也可以配置多个
    # 参考文档：https://blog.csdn.net/weixin_44141495/article/details/110160186
    # 参考文档：https://www.jianshu.com/p/c8ac84e820cc
    gateway:
      discovery:
        locator:
          # 即使开启了动态获取URI的方式，一旦项目中微服务数量达到几十上百个的时候，配置中任然要写很多配置，这个时候就可以使用服务名称转发，与服务发现组件相结合，通过serviceId转发到具体的服务实例上去。
          # 默认匹配URL /微服务名称/** 路由到具体的微服务。
          enabled: true # 开启基于服务发现的路由规则：是即与服务发现组件相结合，通过serviceId转发到具体的服务实例上。
          lower-case-service-id: true # 设置serviceId大小，默认大写，为true即改为小写
      routes:
        # homepage-service路由转发配置
        - id: homepage-server
          # lb表示从注册中心获取服务
          uri: lb://homepage-service
          predicates:
            # 如果请求地址满足/homepage/**,则将请求转发到homepage-service服务
            - Path=/homepage/**
          # - Cookie=mycookie,mycookievalue # 暂时不用对cookie进行校验
          filters:
            # 去除原请求地址中从左往右的n级路径【n为StripPrefix配置的value值】。实际上是计算机中的左闭右开原则(0,n]，所以本质意思是从0~n-1级路径被割舍
            - StripPrefix=1
            # 熔断降级过滤器回调处理配置
            - name: Hystrix
              args:
                name: homepage-fallback
                fallbackUri: forward:/homepage_fallback

        # onlinemarket-service路由转发配置
        - id: onlinemarket-server
          uri: lb://onlinemarket-service
          predicates:
            - Path=/onlinemarket/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: onlinemarket-fallback
                fallbackUri: forward:/onlinemarket_fallback

        # 登录路由的配置
        - id: auth-server
          uri: lb://auth-service
          predicates:
            - Path=/login/**
          filters:
            # 转发到鉴权服务时，改写请求uri，在原URI前面添加一级'/auth'
            - PrefixPath=/auth
            - name: Hystrix
              args:
                name: auth-fallback
                fallbackUri: forward:/auth_fallback

          # api接口访问路由的配置
        - id: api-server
          uri: lb://auth-service
          predicates:
            - Path=/api/**
            # 进行请求头的token检测
#            - Header=Zypw-Token, \w+
          filters:
            - PrefixPath=/auth
            - name: Hystrix
              args:
                name: auth-fallback
                fallbackUri: forward:/auth_fallback