server:
  port: 12023
spring:
  application:
    name: zypw-profile-service
  datasource:
    url: jdbc:mysql://localhost:3306/zypw_test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123789Xlys!@#$
  jpa:
    show-sql: true


