server:
  port: 12022
spring:
  application:
    name: onlinemarket-service
  cloud:
    nacos:
      # 服务注册发现中心
      discovery:
        server-addr: 139.9.121.3:8847,139.9.121.3:8848,139.9.121.3:8849

